### ISSUE TITLE
FS17 upgrade?

### ISSUE THREAD

**Issue by DeckerMMIV** [DeckerMMIV/FarmSim_Mod_BalerAutoUnload#2]
Your question: Is this going to be upgraded to FS17?

My answer: Yes it is. - Hopefully available via the in-game mod browser.

**Comment by quessith** [comment]
Hope it arrives soon, realy loved this mod for FS15 so can't wait till it arrives for FS17 :D

**Comment by DeckerMMIV** [comment]
It is available on the ModHub at Farming-Simulator website
