### ISSUE TITLE
Block mod

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [DeckerMMIV/FarmSim_Mod_BalerAutoUnload#9]
If the folder mods there are "Creator Tools" mod, then your mod does not work.
http://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=69742&title=fs2017
There are many key conflicts. :(

**Comment by DeckerMMIV** [comment]
Okay. I will take a look at it.

Also please note, that I had just sent Giants an e-mail with the mod-update, and only saw your pull request after that. - So I do not yet know if your translations are actually included in the 1.1.0.24. Depends on how fast Giants have been to download from my Dropbox.

**Comment by Gonimy-Vetrom** [comment]
I understood.

**Comment by DeckerMMIV** [comment]
Having my 'Automatic Unload for Round-Balers' and that other 'Creator Tools' mod enabled, it does not look to me that there are key conflicts with the action IMPLEMENT_EXTRA4 (default key 'Z').

However the 'Creator Tools' does have some annoying idea of having key 'G' binded to its "settings screen". So I guess you should just remap the controls.

**Comment by Gonimy-Vetrom** [comment]
I was annoyed, too.
